### ISSUE TITLE
Mouseover display not working on specific character.

### ISSUE THREAD

**Issue by Murtogg** [cr4ckp0t/ElvUI_MythicPlusDatatext#2]
Experienced an issue where the mouseover was not working on a specific character. After enabling script errors it called an error on line 235 of the ElvUI_MythicPlusDatatext.lua file.  After looking at the lua file, the offending piece of code is a duplication of an array variable on line 235. 

Code contains the following variable call: "affixInfoaffixInfo.level"
which should be updated to: "affixInfo.level"

After fixing this line the mouseover was working properly

**Comment by cr4ckp0t** [comment]
This will be fixed in latest release.
